spring:
  datasource:
    url: jdbc:mariadb://13.49.230.129:3306/allocator
    username: root
    password: 1q2w3e4r!
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  h2:
    console:
      enabled: false
  
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
  
  mvc:
    format:
      date: yyyy-MM-dd

server:
  port: 8080

aws:
  accessKeyId: AKIAWBU2BVNU3HNIF2X3
  secretAccessKey: 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
  region: us-east-1

bedrock:
  model-id: anthropic.claude-3-sonnet-20240229-v1:0