spring:
  datasource:
    url: jdbc:mariadb://13.49.230.129:3306/allocator
    username: root
    password: 1q2w3e4r!
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  h2:
    console:
      enabled: false
  
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
  
  mvc:
    format:
      date: yyyy-MM-dd

server:
  port: 8080

bedrock:
  api:
    key: bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29tLz9BY3Rpb249Q2FsbFdpdGhCZWFyZXJUb2tlbiZYLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFTSUFXQlUyQlZOVVJPRkRXSzdSJTJGMjAyNTA5MzAlMkZldS1ub3J0aC0xJTJGYmVkcm9jayUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTMwVDAwMTg0OVomWC1BbXotRXhwaXJlcz00MzIwMCZYLUFtei1TZWN1cml0eS1Ub2tlbj1JUW9KYjNKcFoybHVYMlZqRUZnYUNtVjFMVzV2Y25Sb0xURWlSekJGQWlBQ0lSVE9NdFNGQndGRjZpdkQ4S3MwblJqNnFOQk5RWFlnSEllNHNyR3RwUUloQUpSbWhEWVdPdjBuJTJGM0ZJV0hBd25PbmJuTnRjT2VHQlc3ZnFCeDY5S2tqc0tzY0RDT0glMkYlMkYlMkYlMkYlMkYlMkYlMkYlMkYlMkYlMkZ3RVFBQm9NTkRFMU9EWXhNVFUyTnpFeklnemRGc1JZOU1kTlBaYmROSGNxbXdNYTd3SCUyQm5GcGlVS0hicHhKU2FBTWxvbU9XSGRkNkRMZU52JTJCNVhHbzhUJTJGbzRud1hhUHhCbzVXTG0xWjBGV2VsVVZ1WG0lMkZQJTJGUUplM0dOR3p6TnV2UWFiZmZZUjhIUUltU1YydTByU2lhUm9LeXVxakwlMkJxaVlJcmQlMkJYTDRoMEhwcHhraTYlMkJFUG1KQktwV0tzR3NWQmZSSTRnVVFkYm9mcXI4RWRpblBUJTJCUU12MnNqQ3Z5TXZPQVNHZzdFOGtlMTRDeTE1RUlXNEEyZyUyRkklMkJxTXVOZDY4TmRHSHhyNU1VRng1dHZZZXpzeExZJTJCNWhuczVlUVg1REVuZ2pQYWxwSWJUZUFXUiUyRjNBVU1oUmlVRGRXV1U2amNaWUozUVgxNDlob3VJaEtJWmJac2RsOW5GbFpqZ2VDTFlZNURjSENZSFRzJTJCYXV3eGlUalpHZUhnYzFHR1NUQ3dWVWVNZWJhMjZXOFFyUlNQREpNa09lR1hZNjh2WExmViUyRkNETWcwazJLdSUyRjN2d1ZLUXRnemtDQlBKcHhQSGlFRnoyZkx0OUglMkI1OVNuRmZ6VzREMTZLNktRYm1Ma2xrcmVSdVVSWE5ZZTFFc0tTejFxblglMkJiV29qaDZqODhYaEc3VWhjODczQ3dzZXBrZXdqV2p0dGpYcDJUR1QyRkZlckF4T21yTWdhTUVaZFQ3NjA4WXdpd2ZUV0QyRHo4U2oySnZKZHRvTE9TSkJLMXBGVmt3dExMc3hnWTYzZ0pkem5vYWR4RzBIQlVtJTJGcDdpMlhaUE5kQmdvJTJGdHZISjVIblVldmlHZlNPJTJCJTJCJTJGcjFuVjVJd1pTZGlJaTM1V3c2UnlWN1F0JTJGVjlPdWhMVVUwSjRQOXNGaDNYbFFWTU5WMmZHQ3lscXpWZVA1MlV2SG9yZTZCMHBvU2ZwcUtPb0h4MEl2ajdMdkpNTWtBUXJINjdwcHNoMFZ1M1ZRN3ZNc1RaSElwckR3TENGSGl0NFFPRTRBa1R1bno1dTl3RG9zVjgwaUNDNEE4U0YlMkZHJTJCSUdHejFRU05RUjk4SCUyQjliREtYd0FsMGVCa1ZoRHZaVCUyQk1tdkIxd0IlMkZJbzdvVkhjUGRzeURIeTQ4VDZiZFd3NXM2VlJUN2c0Y0FkNEFld2FsV1JXNmxMa3o5NXoyJTJGeDBZY2ZhSUMzbWdhUWUlMkZhdEIxczlVVE1xY1pkaGVqMFNjbGthZU5PejdHYWFjaU43QkNoMWdmSGxJTnlENVNhckRNVDZodzNXcHJIWmNOdWYyOXdEM3ZTdmQ5VDBIeFhZQnhUb24wU2dTRk9CVXB3WXdoQmNuTDdUSmdYYkRJNjBTOWYlMkIlMkZtUUVBeVJJNkNoNXhMcVIlMkJpckZBT3RmdHg5TjR6eVEzQWtRJTNEJTNEJlgtQW16LVNpZ25hdHVyZT00OGFhZWE3NjRlNTBkYzE2OTlmNDBjNmY2NDBiODY4MDZiZTllMmU3MjQ5ZjU3YjE5NDg0MzgxYzI3Nzg2YTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZWZXJzaW9uPTE=