name: CD to Ubuntu Server

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file employee-management/pom.xml

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 13.49.230.129
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "employee-management/target/*.jar"
          target: "~/"
          rm: false
          timeout: '30s'
          command_timeout: '10m'
          use_insecure_cipher: false
          debug: true


      # 앱 포트로 실행된 jar 파일 종료
      - name: Stop existing Spring Boot application A
        uses: appleboy/ssh-action@master
        with:
          host: 13.49.230.129
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Stopping existing application..."
            pid=$(lsof -t -i:8080) && kill -9 $pid || echo "No application running on port 8080"

      #앱 포트로 배포 한 jar 파일 실행
      - name: execute shell script A
        uses: appleboy/ssh-action@master
        with:
          host: 13.49.230.129
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            echo "Starting new application..."
            nohup java -jar ~/target/employee-management-1.0.0.jar > app.log 2>&1 &
            echo "New application started. Check app.log for details."